apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp02-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp02
  template:
    metadata:
      labels:
        app: webapp02
    spec:
      imagePullSecrets:
      - name: regcred  # <-- This is the Docker login secret
      containers:
      - name: webapp-container
        image: mikecabalin09/mikejc30:build-2  # <-- Replace with your actual image/tag
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp02-service
spec:
  type: LoadBalancer
  selector:
    app: webapp02
  ports:
  - port: 8080       # external port
    targetPort: 80   # container port
