apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp02
  template:
    metadata:
      labels:
        app: webapp02
    spec:
      containers:
      - name: webapp-container
        image: mikecabalin09/mikejc30:build-2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp02-service
spec:
  type: LoadBalancer
  selector:
    app: webapp02
  ports:
  - port: 8080
    targetPort: 80
